// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMha75IekYl7qFuhnmOIFDMyRY7nrdRK0',
    appId: '1:1023518605937:web:fb6423bd63cc473fd6d1d0',
    messagingSenderId: '1023518605937',
    projectId: 'myfitnesspal-6fa14',
    authDomain: 'myfitnesspal-6fa14.firebaseapp.com',
    storageBucket: 'myfitnesspal-6fa14.appspot.com',
    measurementId: 'G-JNNH3T7DLZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8KUSCX_xxfl8mrceq8p_WcylyCTHukP0',
    appId: '1:1023518605937:android:33931df7a0eaf2a9d6d1d0',
    messagingSenderId: '1023518605937',
    projectId: 'myfitnesspal-6fa14',
    storageBucket: 'myfitnesspal-6fa14.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyoJ4QE75h8e17OLy1XI74KxJM7rtssZI',
    appId: '1:1023518605937:ios:414ed52fddf4d47fd6d1d0',
    messagingSenderId: '1023518605937',
    projectId: 'myfitnesspal-6fa14',
    storageBucket: 'myfitnesspal-6fa14.appspot.com',
    iosBundleId: 'com.example.myfitnesspal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyoJ4QE75h8e17OLy1XI74KxJM7rtssZI',
    appId: '1:1023518605937:ios:414ed52fddf4d47fd6d1d0',
    messagingSenderId: '1023518605937',
    projectId: 'myfitnesspal-6fa14',
    storageBucket: 'myfitnesspal-6fa14.appspot.com',
    iosBundleId: 'com.example.myfitnesspal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMha75IekYl7qFuhnmOIFDMyRY7nrdRK0',
    appId: '1:1023518605937:web:b636922bede20407d6d1d0',
    messagingSenderId: '1023518605937',
    projectId: 'myfitnesspal-6fa14',
    authDomain: 'myfitnesspal-6fa14.firebaseapp.com',
    storageBucket: 'myfitnesspal-6fa14.appspot.com',
    measurementId: 'G-LCFQEDSEVJ',
  );
}
